### ISSUE TITLE
URL Hijacking Description + more

### ISSUE THREAD

**Issue by vampiricwulf** [dnsev/4cs#10]
https://github.com/dnsev/4cs/blob/master/web/4cs.user.js#L10962
What does that even mean?
https://github.com/dnsev/4cs/blob/master/web/4cs.user.js#L8679
Why not apply a class? (i.e. MPMassSound)
Is there a specific reason you use `div` rather than `span`?

**Comment by dnsev** [comment]
Quick version:
1) Related to [ihavenoface's 4chan x](http://ihavenoface.github.com/4chan-x/) and is ultimately a useless and redundant feature (which is default disabled).
2) ~~Not sure what you mean; clarify?~~ Nevermind, I think I deduced the issue. [Here](https://github.com/dnsev/4cs/blob/6511357b7d1c243b2de85246d01be0d971f950e5/web/4cs.dev.user.js#L1704).
3) Original design used it more often, ease of typing, [this](https://github.com/dnsev/4cs/blob/master/web/MediaPlayer.js#L3820), and no particular reason

---

Long version:

1) That was a small addition that I added when I started using [ihavenoface's 4chan x](http://ihavenoface.github.com/4chan-x/) when I noticed that version of the script does auto-embedding, which either the one I had didn't have, or wasn't enabled.

What it does is it allows 4cs to retain it's hover preview along with the [embed] link next to it. It was a bit iffy when I was working on it because of how 4chanx handled the link replacement (my script wouldn't work on the first get of the link, but subsequent get's would) and I didn't really look into it because the URL replacement can be disabled in one of the two if undesired.

To actually answer the question, when enabled, it removes "[embed]", and when disabled, it doesn't; enabling it is the same as disabling 4chanx's URL replacement, which is why this feature is default off.

<br />

2) Do you want a class on that div that contains it? That seems like it might be it, so I'll do that.
`MPThreadControls` @ [4cs.dev.user.js](https://github.com/dnsev/4cs/blob/6511357b7d1c243b2de85246d01be0d971f950e5/web/4cs.dev.user.js#L1704)

<br />

3) I used `div`'s a lot more commonly while originally designing the css of the media player itself. In MediaPlayer.js, the shortcut function `D()` created a div, and I didn't see a need to add one for span.

In the main file, I guess `"div"` was less characters than `"span"`, and for consistency with the above statement.

So overall, no reason in particular; they can both accomplish the same thing.

**Comment by vampiricwulf** [comment]
1. Oh, that makes sense. I just disabled noface-x's linkify as the one in this is better.
2. Thank you very much.
3. Mind changing that one segment to `span`?
   It's kinda annoying to deal with in the css, I border every `2n` thread to show where a thread preview begins and ends. Since this line is marked as `div`, it throws the count off by one due to it being in the hierarchy where `.thread` is located and all those are `div` as well.

**Comment by dnsev** [comment]
[Changed](https://github.com/dnsev/4cs/blob/012ba399fafd453dd0e3bdb59dfab38f7211e719/web/4cs.dev.user.js#L1703)

**Comment by vampiricwulf** [comment]
Thank you. I'll make sure to notify you if I find anything else.
