### ISSUE TITLE
4cs is incompatible with Appchan X, no way to enter the captcha

### ISSUE THREAD

**Issue by Lyrica-Prismriver** [dnsev/4cs#13]
While, or any time after, a sounds image is selected with "browse" and it's info shows up, I am unable to enter the captcha, I have to reload the page for it to work.  The only way I can post sounds with Appchan X is to enter the captcha, then select the sound image and press "submit", then reload the whole page (breaking any sound that's playing), and repeat for each image.  Is there any way to disable the Appchan X/4cs "fusion"?

http://www.pictureshack.us/images/49803_borked_player.png

**Comment by dnsev** [comment]
You can disable the uploader in the settings if the problem persists.
1. Does this happen only after you've <i>uploaded</i> a sounds image, or does it happen before you even upload anything?<br /><br />
2. In what way doesn't it work? Can you just not type in the text field, or does it disappear?<br /><br />
3. <p>From the image, it looks like that's taken after you've submitted an image. What my script tries to do is force you to manually reload the captcha by clicking on the image, otherwise it messes with the original userscript. If this is what you mean, just click to reload (I'll make this more clear too.)</p>
   <p><i>I have fixed this "issue"; captcha should now [automatically reload](https://github.com/dnsev/4cs/blob/670305472ce92531c4dc7b5cf03fbf056334f52a/web/4cs.dev.user.js#L3359-L3360) after you submit.</i></p><br />
4. Make sure you've updated to the newest version; this is a very recent development, and very recently I fixed a bunch of things which didn't work for some person(s).
   I say this because of how your submit button seems to be flying off into space, and the style resembles an issue I tried to fix.<br /><br />
5. What browser?<br /><br />
6. Also, what theme or whatever are you using? I'm not all that familiar with appchanx.<br /><br />

**Comment by Lyrica-Prismriver** [comment]
<i>>Does this happen only after you've uploaded a sounds image, or does it happen before you even upload anything?</i>
It prevents me from uploading as soon as it detects there's a sound file and tries to change the layout of the QR box.   So if I've already typed in the captcha I'm in luck and can press submit, but after that I can no longer enter the captcha, so can no longer post.

<i>>In what way doesn't it work? Can you just not type in the text field, or does it disappear?</i>
I cannot click on the field to enter captcha.

<i>>What browser?</i>
Chromium    26.0.1386.0 (Developer Build 177362) Ubuntu 12.10

<i>>Also, what theme or whatever are you using? I'm not all that familiar with appchanx.</i>
Photon, I think.  Whatever this one is: http://www.pictureshack.us/images/36272_selected.png

~~Also, can I not greentext here?  I can't even post > correctly...~~

**Comment by vampiricwulf** [comment]
>Can I not greentext here?

`\>` is how.

**Comment by dnsev** [comment]
I tested this on Chrome (should be close enough to Chromium) and this was my result: [image](https://f.cloud.github.com/assets/3087287/211107/dba5a348-82a9-11e2-8415-186048cf75dc.png)

Again, it looks like from your original image that your version was using an older animation style, which broke a lot of things. (Notice how the `Sounds`/`Spoiler Image` controls are on the same line as the `Submit` button in your image; this was changed.)

Make sure you've updated to the newest version (3.1.2 at present) and see if the problem persists.

---

And if it does, all I can suggest from there is inspecting the element like so: [image](https://f.cloud.github.com/assets/3087287/211155/fbf1c1ee-82aa-11e2-930f-1cbe03b6ee2a.png)

And you should get a popup near the bottom with a line highlighted. Copy the text or a screenshot of what that line says; mine looks like so:

``` html
<input title="Verification" class="field" autocomplete="off" size="1" placeholder="Verification (Shift + Enter to cache)" alt="0">
```
