### ISSUE TITLE
4cs interferes with the cooldown timer on Appchan X, and prevents the file name from vanishing

### ISSUE THREAD

**Issue by Lyrica-Prismriver** [dnsev/4cs#14]
The quick reply for Appchan X is being messed up by 4cs again...  Now, after a sound image is posted, the cooldown timer doesn't start, so I have to manually gauge how long between posts.

Also, the filename doesn't disappear from the quick reply box automatically after it's posted like it should.

Oh, it also seems to prevent me from stopping an upload in progress...

**Comment by dnsev** [comment]
1) The cooldown timer may have been affected because my script tries to "click" it after it posts. It now waits 1.5 seconds after posting before doing so, and you can disable this feature in the settings.

The reason this is necessary is because it isn't posting through appchanx; 4cs has to create and post all the data itself. It's a mess.

2) This should be fixed now.

3) This is not implemented (yet?)
