### ISSUE TITLE
Embedding videos...

### ISSUE THREAD

**Issue by Lyrica-Prismriver** [dnsev/4cs#15]
Example (only works in 4cs, not just the browser)
http://i50.tinypic.com/14j9hqc.jpg

WHAT IS THIS WIZARDRY?

It's a jpeg, but it plays some kind of video...

**Comment by dnsev** [comment]
http://dnsev.github.com/ve/

**Comment by Lyrica-Prismriver** [comment]
Ah thank you.

You should probably make it more clear in updates for 4cs that this works, me and many other /a/nons were quite confused when a few jpegs started playing movies...

Will ve ever be integrated into 4cs?

**Comment by dnsev** [comment]
I noticed.

It's in the [changelog](http://dnsev.github.com/4cs/#changes) for what it's worth, but when the userscript updates (particularly automatically,) it doesn't really display any info about what's changed, because usually it's fairly minor and people won't care about it.

Also, there was not really any major "announcement" because 1) this is a very recent development, 2) word seems to be spreading on its own from what I've observed, and 3) I don't really have any means of announcing it anyways.

Integrated? What do you mean by that; the playback support is obviously integrated, as is downloading of the resources. The only thing not supported yet is uploading detection similar to sounds, which is planned but not started yet.
