### ISSUE TITLE
Appchan X Compatibility

### ISSUE THREAD

**Issue by zixaphir** [dnsev/4cs#16]
Yo, your script has interoperability issues with mine (https://github.com/zixaphir/appchan-x/). I could fix it on my side, but it'd be considerably easier to patch on yours. Essentially, I'm asking a favor (please!). My script strips 4chan's default CSS by removing all style elements and link elements with a Style/CSS ref, providing they don't have an ID. If you could just add an ID to any style elements your script inserts, mine would simply ignore them.

I've tried writing in workarounds and various checks to try to prevent non-4chan default CSS from being removed on my side, but unfortunately they're very inconsistent, partially due to the inline extension's insistence on adding its CSS whether or not it's enabled.

This would be a huge favor to me and our users. Thanks.

**Comment by dnsev** [comment]
~~Am I correct in assuming this problem is majorly affecting the media player "window" part of the script, or the inline portions, such as post modifications or the uploader? And when you say "removing all style elements," do you mean it removes the `style` and `class` attributes of all un-id'd elements? (I only ask because in the places I've checked while appchan-x is enabled, my added classes are still there, so I might be misunderstanding.)~~<br /><br />

Thus far I've been doing as much as I can to get it to work with some of the other big userscripts it seems people use, such as yours, a few other variations of 4chan-x, the inline extension, and so on; I feel it's more of my job to get it to work with already established userscripts. A lot of the styling issues I've encountered so far have mostly been solved with !importants and other CSS priority stuff.<br /><br />

~~Also, do you have any specific setup for testing which causes the most problems with mine? Browser, particular style chosen in the script, execution order of them maybe (although every time I mess with this, nothing changes.)~~

---

I just updated my appchan-x and there's a few more issues that weren't there before that I'll get on fixing, and also look into the conflicts you mentioned.

And I think I see what you mean when I use Chrome; there's a hell of a lot more problems than when I test on Firefox.

**Comment by dnsev** [comment]
Should be fixed in [4.4](https://github.com/dnsev/4cs/commit/3c133bac07e68b793eae2dc104754e2185a1324c). Let me know if you see any more glaring issues; it works a lot better for me now at least.

**Comment by zixaphir** [comment]
Everything is looking fine over here. Thanks again
