### ISSUE TITLE
MP3 support

### ISSUE THREAD

**Issue by Matrius** [dnsev/4cs#21]
This may be a long shot, since I don't really even know how 4cs works, or how it masks it's sounds in the images, but would it be possible to embed mp3 files in images too and play them? There's a javascript audio library called howler.js you may want to know about
http://goldfirestudios.com/blog/104/howler.js-Modern-Web-Audio-Javascript-Library

**Comment by dnsev** [comment]
I've actually thought about that on more than one occasion, though I didn't find a suitable Javascript mp3 player. I'll look into that though, thanks for pointing that out.

Ultimately it will depend on how good the performance of the library is; if it's pretty good, it'll probably happen at some point.

**Comment by dnsev** [comment]
So from what I understand, it looks like the Howler.js is only a wrapper for the Javascript `Audio()` object and html `<audio>` tags. So ultimately, mp3 support still relies on the browser.

The problem is, Chrome supports mp3, Nightly supports mp3, but Firefox does not. And moving on to the option of using a Javascript mp3 decoding library, the issue I've seen with this is poor performance on Firefox. If you switch tabs during playback, the audio stutters pretty badly, which is pretty annoying. [link](http://audiocogs.org/codecs/mp3/)

**Comment by Matrius** [comment]
Oh I see, thanks for clearing that up.
