### ISSUE TITLE
Cannot post my own embedded images, and posting others is very difficult

### ISSUE THREAD

**Issue by ghost** [dnsev/4cs#22]
I followed the guide on the download page and got my embedded image, but when trying to post the image on 4chan, it still knows I have an embedded image. What's more, is that whenever trying to post an embedded image that I saved from another poster, I have to put in the captcha on avereage about 20 times.

I have 4chanx V3, 4cs 4.5.2 , and I used Ogglify. 4chanX is on Greasemonkey, and 4cs is on scriptish, though.

edit: changing the 4cs install to greasemonkey didn't help

**Comment by dnsev** [comment]
For your own images: this is probably due to filesize:dimensions restrictions. Try [upscaling your images](http://dnsev.github.io/4cs/#bigger) after you've used the guide to make them.

For other images: using 4chanx V3, currently you have to manually check the "sounds" checkbox to upload old ones that are in the wrong format; this is not done automatically yet. If they are in the proper format, then they should be postable; I just tested this with a .gif and it worked.

If you're getting something like "connection error" when posting, that's moot's problem. If you have any files for me to test with, you can post them in here and I'll see if there's any problems.

**Comment by ghost** [comment]
Well I guess bigger might have worked, or not. I still can't post images, and sometimes, instead of failing captcha, my post gets through to the thread sans image, so there's just text.

Edit:I got it to work, I think you have to put in the entire captcha, rather than just the warped word, although I don't know for sure.
