### ISSUE TITLE
Why not .gif instead of bigger?

### ISSUE THREAD

**Issue by vampiricwulf** [dnsev/4cs#27]

**Comment by dnsev** [comment]
Quality and file size control, don't have to worry about limited colors, same file extension. .png's also keep any transparency.

I'm not sure if the C++ libraries I used can export to .gif, but I already had the code for .png and .jpg exporting, so that was faster.

I tried to get this made quickly after it was demanded, so I just went with the obvious solution rather than having to worry about testing file sizes with .gif outputs.

**Comment by vampiricwulf** [comment]
Makes sense. Thanks for the quick response.
