### ISSUE TITLE
Batch Downloading Mass files

### ISSUE THREAD

**Issue by snowboundmage** [dnsev/4cs#28]
Doesn't seem work on with very large playlists, 50 or so seems fine, but 100+ just doesn't do anything. Clicking it has seemingly no effect. Is it a loading time, or can it not handle large playlists?

**Comment by dnsev** [comment]
Do you get anything in your error console (ctrl+shift+k in Firefox, ctrl+shift+j in Chrome) when you do this? I just tested on a list of 100 sound/video files, and it generates the links (albeit after a bit of time sometimes.)

Video links won't appear in the download either because they're detected as a "non-sound" playlist item, so keep that in mind too.

One reason I can think of that causes this would be that it has to go re-fetch and re-read all the image files if you're downloading by image. (It's always a pain in the ass to test this because there's always problems related to this that seemingly silently error.)

**Comment by snowboundmage** [comment]
Alright, i did a bit more "investigating", and 150 seems to be about the limit, 200 seems completely hopeless, with no errors in the console.

Also, firefox with greasemonkey, all updated

**Comment by dnsev** [comment]
Actually, now that I think about it, it might be due to memory limitations of either your computer, Firefox, or it's Javascript implementation. For 150 some sounds, assuming every sound is ~2mb, it would need to create some temporary storage of 300+ MB to build the .zip file, which maybe it isn't allowed to do. Can't really say for sure, but maybe trying to build a file that large isn't possible.

**Comment by snowboundmage** [comment]
Ill close the issue anyway, but yeah, that seems to be the explanation. Thank you.
