### ISSUE TITLE
XMLHttpRequest cannot load

### ISSUE THREAD

**Issue by Pynkato** [dnsev/4cs#29]
XMLHttpRequest cannot load http://images.4chan.org/v/src/1370570732918.jpg. Origin http://boards.4chan.org is not allowed by Access-Control-Allow-Origin. I found this error by pressing ctrl+shift+j in Chrome and it shows the same error every time I press [sounds] next to the image name. The media player isn't working at all for me, it just gets stuck loading. Anybody else having this issue? Can I get some help?

**Comment by dnsev** [comment]
Follow step 3 for the Chrome install directions on the [homepage](http://dnsev.github.io/4cs/):

Edit your Tampermonkey settings:
-    Go to the Tampermonkey Dashboard page
-    Open the Settings tab on the right
-    Under General, change "Config mode" to "Beginner"
-    Under Runtime, change "UnsafeWindow retrieval method" to "Proxy"

(You have to do this because of some stupid security setting Google Chrome changed that nobody cares about.)
