### ISSUE TITLE
player not working

### ISSUE THREAD

**Issue by ggeecckkoo** [dnsev/4cs#31]
i'm using chrome with tampermonkey, have no other scripts besides this one and sound uploader
when i'm clicking on embedded youtube links they just opens in another tab and refuses to play in the media player. sound files works perfectly though.
have tried resetting the settings, refreshing the page and re-installing the script.

**Comment by dnsev** [comment]
Did you try:
-    Go to the Tampermonkey Dashboard page
-    Open the Settings tab on the right
-    Under General, change "Config mode" to "Beginner"
-    Under Runtime, change "UnsafeWindow retrieval method" to "Proxy"

**Comment by ggeecckkoo** [comment]
yes

**Comment by dnsev** [comment]
Well first of all, the sound uploader extension isn't necessary anymore; 4cs has one included in it.

Second, I'd recommend checking the error console (in the tab running the extension) after you've clicked a link and see if anything pops up.

Also make sure that under your [Settings] -> Link Replacement, "Media URLs ..." options are enabled.

**Comment by ggeecckkoo** [comment]
found the solution, had to go in chrome://flags and enable experimental javascript and relaunch the browser in order for 4cs to work

Edit: It appears that this only fixed the issue with the script opening the embedded youtube video into tab, but the video won't load into the player.
I checked the console and saw "Uncaught Error: NotFoundError: DOM Exception 8" with "DOMException {message: "NotFoundError: DOM Exception 8", name: "NotFoundError", code: 8, stack: "Error: An attempt was made to reference a Node in …pobfkfo/content.js:49:48))), <anonymous>:8105:20)", INDEX_SIZE_ERR: 1…}" above it
So I digged a little further and found out that the error was related to this line: "window._unsafe.tag.parentNode.removeChild(window._unsafe.tag);".
![20 -v- - good bossfights](https://f.cloud.github.com/assets/4706342/661560/68306b46-d736-11e2-93e0-9768d2bd7544.png)
![22 -v- - good bossfight](https://f.cloud.github.com/assets/4706342/661579/c12ba9fe-d736-11e2-91b0-a74c38e0ff8c.png)

i do not know what this means

**Comment by dnsev** [comment]
> found the solution, had to go in chrome://flags and enable experimental javascript and relaunch the browser in order for 4cs to work
> That is really odd, I -- actually I found out why that was happening, and that was a "bug" in my script.

The bad news is this doesn't look fixable since chrome apparently did something awful to userscripts security-wise not so long back. Trying to code and communicate with embedded YT/Vimeo/Soundcloud content has always been a pain in Chrome, and has mainly worked by a Javascript hack.

Trying to fix this for Chrome looks like it would involve having 2 window communication buffers which isn't something that looks very fun to try and do; so I can't promise I'll fix this soon (if at all) for 4cs.

---

For now, the easiest thing I can suggest is either:
- Disable YT/Vimeo/Soundcloud playback in 4cs and install:
- 
  - One of the forks of 4chan-x that support inline embedding of videos,
  - Or I think the inline extension might do that too, if you're more comfortable with that
- Use Firefox, as it works fine there

**Comment by ggeecckkoo** [comment]
ok, none of those worked but i have changed my browser to firefox and everything is working perfectly, for the moment.
