### ISSUE TITLE
Playing video from older steganographic format

### ISSUE THREAD

**Issue by writen-unclear** [dnsev/4cs#36]
Would it be possible to have the media player play .webm videos that have been embedded in the pixel data of an image with the old embed.exe encoder rather than with Videncode?  It seems like it would be relatively easy to add, and it could be a valuable fallback in the likely eventuality that 4chan starts using slightly better filtering.

**Comment by dnsev** [comment]
Technically yes, but practically it would probably be worse and definitely not worth doing at this point.

---

First, it's not just .webm videos that Videncode embeds, so it wouldn't have identical functionality just by doing that, and adds a slight bit of complexity for implementing into the userscript.

Second, doing this would require the use of .png images, which would cause the following problems:
- Image file has tons of noise due to trying to fit a larger image<br />
  Most of the Videncode files created are very near 3 MB, with the image being a few KB of the full size (becasue jpeg,) so trying to pack more data into the .png
- Video quality greatly degraded due to size new constraints
- Longer encoding times to create a nicely sized .png (embed.exe suffers this problem when creating an optimal .png)
- Longer decoding times for the userscript (potentially every format)

Lastly, the format will probably be kept as it is currently because it allows better picture and video quality than stego, and because I doubt 4chan has the resources to test every image as it is currently. Even if non-stego images get blocked, video images were more of just an experimental bonus anyways.
[It's great for making [HD versions](https://0-media-cdn.foolz.us/ffuuka/board/a/image/1372/13/1372139183999.gif) ([embed](http://dnsev.github.io/4cs/play/)) of what may have originally been a .gif file; not so great at things 1:30 or longer, give or take depending on how busy the video is.]
