### ISSUE TITLE
4cs blocked by javascript?

### ISSUE THREAD

**Issue by ghost** [dnsev/4cs#41]
It seems my 4cs wont load and tampermonkey gives me an error saying that my javascript settings or a scriptblocker is blocking it, but I've both disabled my script blocker and set javascrip to allowing java to run on all websites.

**Comment by dnsev** [comment]
Well if Tampermonkey is giving you the error, chances are it's not 4cs's problem.

The only advice I can really give is try removing whatever "script blockers" you have and see if it works, or use a different browser

**Comment by ghost** [comment]
I've already tried disabling both my script blocker and adblock, and 4cs still does not come up

**Comment by dnsev** [comment]
Do any other userscripts work? (e.g. install 4chan x and see if that runs)

**Comment by ghost** [comment]
Yes, 4chanx and my other userscripts seem to work fine, it just looks like 4cs is being effected

**Comment by dnsev** [comment]
Okay then what's the script blocker you use, and do you know whether it's that or adblock that's blocking it (or if it has to be both)? (Try running only one at a time and see if it works to see if it's just one of them causing it.)

**Comment by ghost** [comment]
I mainly just use adblock, but have scriptsafe just in case, i've tried disabling one at a time, and then disabled both and tampermonkey still gives me the error and 4cs still wont load.

**Comment by dnsev** [comment]
So judging from other people having the same error, this seems to be an issue with a Chrome update.

I might try and see if I can get my Chrome browser to update and have this problem happen and see if it's anything in the script making it happen.

Recent Chrome and Firefox updates really enjoy destroying userscripts it seems.

**Comment by dnsev** [comment]
Just as an update on this: after a small bit of investigation, it seems that this is not a 4cs problem and is Chrome+Tampermonkey's problem.

I can't seem to get 4cs to run (or any other userscript) without the error, even if the script consists of only `alert(1);`

So it doesn't seem to be the userscript, it seems to be the fact that it's running through Tampermonkey.

So still I have no solutions though. Not sure what happens if you try to run it through Chrome directly, it hasn't been tested for that. I might check how that works sometime soon.

**Comment by dnsev** [comment]
Another update:

Seems 4cs does work (at least the most important features) as a native chrome extension. Instructions on how to do this have been included on [the homepage](http://dnsev.github.io/4cs/#?all), so feel free to check that out.
