### ISSUE TITLE
Firefox muted

### ISSUE THREAD

**Issue by thedoctorbisin** [dnsev/4cs#43]
I have the latest versions of the 4chan Media Player, Firefox, Tampermonkey and 4chan X running on my computer. When I click the "sounds" link next to the images with sound in them, the player loads the sound file and image and the player registers that the music is being played (like it has the specific playtime and everything like usual). The problem is that no sound actually plays even though the player thinks it is, like the sound has been muted or something. Even when volume is at 100% it still does this.

**Comment by dnsev** [comment]
Odd, I've never encountered such a bug.

Try the test on [this page](http://dnsev.github.io/4cs/#issues/audio), and copy the log it outputs to here.

**Comment by thedoctorbisin** [comment]
Here it is:

Log:

> Interactive event: generate
> Initial volume: 1
> Audio event: durationchange
> Interactive event: play
> Paused status: true
> Audio event: play
> Audio event: pause
> Audio event: ended

**Comment by dnsev** [comment]
And could you hear it playing?

**Comment by thedoctorbisin** [comment]
No, I couldn't.

**Comment by dnsev** [comment]
That's odd. It seems to have clearly played at full volume, because that's the same exact log I get when I run it.

Your browser must have some sort of issue playing the `<audio>` tag, because that test a pretty straight-forward way of playing audio.

Because of that, it doesn't seem to be an error on 4cs part. I would suggest googling the problem and/or reinstalling your browser and/or trying it with a different browser.

**Comment by thedoctorbisin** [comment]
OK I've figured out the problem now and it was all my fault and had nothing to do with 4cs part. I couldn't hear it because in Mixer - Applications Firefox was set to a low volume/possibly muted. I didn't realise this since everything else was playing fine. Thanks for the help.
