### ISSUE TITLE
Youtube: Video not found on appears after a point

### ISSUE THREAD

**Issue by Ninetime** [dnsev/4cs#48]
After a point the Youtube video title will stop appearing and is replaced with Youtube: Video not found on all following links
![4cs youtube video not found](https://f.cloud.github.com/assets/6248582/1801863/4359bb24-6bf1-11e3-80eb-c299369fb6c0.png)

**Comment by dnsev** [comment]
I know why this issue occurs, and I forget if I tried to implement a solution to it or not.

This happens because 4cs queries Youtube's APIs too much (because of all the links) in a short amount of time, and it starts returning a forbidden error code.

This is kind of a rare problem, but I might fix it if I get around to it.
