### ISSUE TITLE
Youtube won't play on player

### ISSUE THREAD

**Issue by DanSleeman** [dnsev/4cs#49]
When I try to load a link from Youtube it brings up the player but doesn't load automatically, and is unresponsive when I click the play button. I have not had any problems loading embedded sound images and the audio tag test worked fine for me too. Other sites such as Vimeo work fine. I've disabled my adblock and other scripts but that didn't fix anything.
![4chanmediaplayer](https://f.cloud.github.com/assets/6299800/1830549/54498a60-734c-11e3-8d6f-96680aeab56c.png)

**Comment by dnsev** [comment]
Few questions first:

1) What browser?
2a) If you're using Chrome, are you using Tampermonkey or native extension installation?
2b) If you're using Firefox, what version of Greasemonkey?

Second:

The Youtube functionality can be tricky sometimes because of how it uses a Flash player somtimes, and other times a HTML5 player. Since 4cs tries to keep a consistent looking user interface for the player, it tries to "override" the default Youtube player controls. This is do-able, but has been problematic in the past with different versions of different browsers.

Additionally, the Youtube player itself can have a mind of its own sometimes, such as when resizing the player, the Youtube video may try to change the video quality automatically.

**Comment by DanSleeman** [comment]
I am running Firefox 26 with Greasemonkey 1.13

**Comment by DanSleeman** [comment]
I found a way to get it to play YouTube files, It works when I sign out of my you tube account. I don't have any idea why, but I've tested it on multiple computers and that is the only way I can play videos.

**Comment by dnsev** [comment]
Interesting. I'll try playing around with signing into and out of accounts and see if that does anything on my end, but I haven't replicated the problems thus far.

**Comment by dnsev** [comment]
So I tried all combinations of signing in/out, enabling HTML5 player by default/not, and using http/https, and I couldn't get videos to not work.

[Everything has worked so far for me, so I don't know what the problem is.](https://f.cloud.github.com/assets/3087287/2033051/6318c156-8917-11e3-8406-53c33c94d303.png)

Also GM1.14 is out, update to that as well.

**Comment by DanSleeman** [comment]
I appreciate all the work you've done to try and figure this out, and for some reason, I can now be signed in to YouTube and play videos. I'm at a loss because it definitely did not work two days ago. Both computers that I've used behaved the same way before and they now both work.
