### ISSUE TITLE
Player won't recognize youtube links when the ?v=XXXXXXXXX has _ or - in it.

### ISSUE THREAD

**Issue by Never22** [dnsev/4cs#50]
Title, I recently noticed in a post that only two links weren't working with the media player and it turned out they were the only ones with a _ and a - in them.
So basically any youtube link with special characters is fucked.

Edit: I really should have tested it before I posted.
That doesn't seem to be the issue.
So fuck me backwards.
Just ignore this.

**Comment by dnsev** [comment]
Related comment I guess, but I think some of the new 4chan-x scripts have been changing the way the index pages work, and I've seen many times 4cs simply not activate on an index page, and sometimes it will.

I haven't looked much into the cause yet since it's so sporadic, but that could potentially be the cause.

(I've done a good job of ignoring this I feel.)

**Comment by Never22** [comment]
Actually I think I've found the issue.
I use ihavenoface's fork of 4chan X, and in it's settings under "Linkification" it has the option "Link Titles: Fetch and replace links with titles of embeddable content.", as soon as I disabled that everything has worked perfectly so far.
I have an issue with this though, the underline on the media player's version of "Link Titles" bleeds into the text and it's kind of annoying. Could you change it?
![divide](https://f.cloud.github.com/assets/2200827/2032054/f37c383a-8909-11e3-95be-8d25998f8a96.png)

**Comment by dnsev** [comment]
Fixed the underline issue in [5.0.0.1.1](https://github.com/dnsev/4cs/commit/ebd93cd978374259af18ce36843af1288346f9d1)/[cl](http://dnsev.github.io/4cs/#changes)

Honestly I'm surprised nobody has pointed that out by now. I completely forgot because my links don't have underlines on.
