### ISSUE TITLE
Doesn't seem to recognize youtu.be links if they don't have the http:// before it

### ISSUE THREAD

**Issue by Never22** [dnsev/4cs#53]
So I was strolling along /vg/ one day when I stumbled on this-
![capture](https://f.cloud.github.com/assets/2200827/2419984/2ae68bce-ab68-11e3-94cf-763482dd54ca.PNG)
4chan X gets the embed right but the movie player doesn't seem to recognize it at all.
I messed with things in my settings to see if it was me but I couldn't find anything so I'm posting here.

**Comment by dnsev** [comment]
Yeah, it seems 4cs doesn't check for links that look like `something.xx`. Mainly because I think that historically, 4chan-x didn't parse those links either. Also I notice a lot of false positives when it does when people forget a space after the end of a sentence.

I can get it updated to hijack links created by 4chan-x and convert them into video links, but I probably won't be making it detect `something.xx` as links, because of the number of regex rules that would need to be written, and how it would introduce the problem above.

Should be updated in [5.0.2](https://github.com/dnsev/4cs/commit/23f5b079d5265d8b8eb074e177abad5ee10aef75)/[cl](http://dnsev.github.io/4cs/#changes?highlight=5_0_2&scroll=5_0_2)
